language: java
jdk:
  - openjdk8
  - oraclejdk8
  - oraclejdk9
cache:
  directories:
    - $HOME/.m2/
stages:
  - clean
  - build
  - test
jobs:
  include:
    - stage: clean
      script: mvn clean -B
    - stage: build
      script: mvn install -Dmaven.test.skip=true -Dmaven.javadoc.skip=true -B -V
    - stage: test
      script: mvn test -B
    - stage: integration
      script: mvn verify -B
